### ISSUE TITLE
plugin is not in the plugin list

### ISSUE THREAD

**Issue by promeneur** [carcass82/gkrellm-nvidia#1]
openSUSE Tumbleweed
gkrellm 2.3.11
libXNNVCtrl 435.21

the plugin "nvidia.so is well in /.gkrellm2/plugins

The plugin is not in the plugin list.

**Comment by promeneur** [comment]
It is not in the plugin list. It is in the plugin options.
If I check "nvidia" then nothing is displayed even if I restart gkrellm.

**Comment by promeneur** [comment]
x:~/rpmd/gkrellm/gkrellm-nvidia-release-1.0.2> nvidia-smi
Tue Aug 30 10:50:09 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 515.65.01    Driver Version: 515.65.01    CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   76C    P0    N/A /  30W |    332MiB /  2048MiB |     38%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1727      C   ...20/Core_22.fah/FahCore_22      325MiB |
+-----------------------------------------------------------------------------+
x:~/rpmd/gkrellm/gkrellm-nvidia-release-1.0.2>

**Comment by promeneur** [comment]
I did a headless installation for the nvidia card.

I use the nvidia card only for computing.

I uninstalled and forbid :
libnvidia-egl-wayland1
nvidia-glG06
x11-video-nvidiaG06

Only stay installed :

kernel-firmware-nvidia
nvidia-computeG06
nvidia-gfxG06-kmp-default

**Comment by promeneur** [comment]
In user-config there is nothing about "nvidia" plugin in the contrary of "cpupower" plugin

**Comment by carcass82** [comment]
sorry for the late reply
i think the problem is that this plugin uses xnvctrl which only exists as an extension of X sessions managed by an nvidia driver.
i was already working to replace libXNVCtrl with NVML (the library also used by nvidia-smi), i'll ping you as soon as a new package is ready

**Comment by promeneur** [comment]
thanks

**Comment by promeneur** [comment]
I have just installed the 1.1 version.

All is ok. the problerm is solved.

It seems the nvml library is installed by installing the nvidia headless version.

Perhaps nvml is in one of the nvidia packages : kernel-firmware-nvidia, nvidia-computeG06, nvidia-GFXG06-kmp-default.

Thanks
